### PR TITLE
Addition to Accomodate ACS2013_5yr Schema, Other Small Improvements

### PR DESCRIPTION
**Pull request by grant-humphries**
In addition to the file specific to the acs13_5yr this commit adds a new meta-function and makes modifications such that ACS product specific information is now provided by the user rather than being hard-coded into some of the existing functions.  The metascripts README is also updated to reflect the changes that I made and to add a few steps that were missing.

### CODE REVIEW

**Comment by JoeGermuska** [comment]
@iandees since you did all the work on this so far, seems like you should review this. It sounds like a welcome contribution, to be sure.

**Comment by iandees** [comment]
We don't really use the .sql parts of the meta-scripts directory for Census Reporter, but if we take out the trimet-specific stuff I can merge this for others that do.

**Comment by grant-humphries** [comment]
I see, so you use the python scripts to generate the sql that's in the 'year-span' folders within the repo.  I would've been open to that as well, but the readme documented the pl/pgsql workflow so I went that route.  Anyhow, this is actually my first pull request so I may be mistaken, but I believe the commit that I submitted only has the generalized additions/improvements that I made and excludes all of the trimet specific code.

**Comment by iandees** [comment]
Welcome to Github! I appreciate the time you put in to making the pull request :smile:.

We do use the python scripts to build SQL. Building SQL with PL/SQL got to be extremely tedious back when I was starting this project, so I switched to a language I'm more familiar with.

If you click on the "Files Changed" tab up near the top of this page you'll see that there are a couple trimet-specific files included in this PR. Getting rid of those files might mean closing this PR and re-opening with those files not in this branch. I'm not sure of the easiest way to do that from your side.

**Comment by grant-humphries** [comment]
Thanks! Am excited to be contributing and your and others work on this project has been extremely useful to me.

I created a new branch in my fork to hold the trimet specific code and rebased master to remove the last commit so I think you should be able to proceed with the merge if the code looks good to you.

**Comment by grant-humphries** [comment]
Hello, just writing to see if your still considering accepting this pull request

**Comment by iandees** [comment]
Sure thing! I didn't notice the changes you had made.

**Pull request merged**
